steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_BRIDGE_URL=${_BRIDGE_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/torxflow-dashboard'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/torxflow-dashboard'
substitutions:
  _BRIDGE_URL: 'https://torxflow-bridge-1041143034967.europe-west4.run.app'
